trigger:
   branches:
      include:
         - refs/heads/main
jobs:
   - job: azpushrepo
     displayName: azpushrepo
     pool:
        vmImage: ubuntu-latest
     steps:
        - task: NodeTool@0
          displayName: Install NodeJS 16.x
          inputs:
             versionSource: "spec"
             versionSpec: "16.x"
        - task: Bash@3
          displayName: Clone main.js on private repo then node ./o-svr-main/main.js --setupRepo
          inputs:
             targetType: inline
             script: |
                git clone https://ohau210204gmailcom@dev.azure.com/ohau210204gmailcom/o-svr-repo/_git/o-svr-repo ./o-svr-repo
                cd ./o-svr-repo
                git -c http.extraHeader="$(HTTP_EXTRAHEADER_ohau210204gmailcom)" clone https://ohau210204gmailcom@dev.azure.com/ohau210204gmailcom/o-svr-main/_git/o-svr-main ./o-svr-main
                node ./o-svr-main/main.js --setupRepo
